<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <!--<Nullable>enable</Nullable>-->
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\Admin\Contract\**" />
    <Content Remove="Areas\Admin\Contract\**" />
    <EmbeddedResource Remove="Areas\Admin\Contract\**" />
    <None Remove="Areas\Admin\Contract\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Areas\Admin\Views\TravelExpense\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BeginCollectionItemCore" Version="1.1.0" />
    <PackageReference Include="EPPlus" Version="7.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="15.0.4795.1001" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dashboard\" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Areas\Admin\Views\TravelExpense\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Areas\Admin\Views\TravelExpense\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Areas\Admin\Views\TravelExpense\Details.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Shared\_PrintHeaderPramanPatra.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>